-- Generated by tools/generate_symbol_manifest.py; do not edit.
return {
  source = {
    repository = "https://github.com/pret/pokecrystal",
    sourceCommit = "3438c7003a57fa2987fcb223d14b660761b33c64",
    symbolsCommit = "0cc2d9450283fedfc43b02809884e77c76a9036c",
    symbolsSha256 = "ca55588e83e4f4974e3872057eec12e8aac853bad1774e91486b5986cf6cb780",
    rgbdsVersion = "1.0.1",
  },
  symbols = {
    ["BaseData"] = {
      bank = 0x14,
      address = 0x5424,
      offset = 0x051424,
    },
    ["BetaMonPicBanks"] = {
      bank = 0x14,
      address = 0x7d84,
      offset = 0x053d84,
    },
    ["CollisionPermissionTable"] = {
      bank = 0x13,
      address = 0x4e1f,
      offset = 0x04ce1f,
    },
    ["Font"] = {
      bank = 0x3e,
      address = 0x4200,
      offset = 0x0f8200,
    },
    ["FontBattleExtra"] = {
      bank = 0x3e,
      address = 0x4600,
      offset = 0x0f8600,
    },
    ["FontExtra"] = {
      bank = 0x3e,
      address = 0x4000,
      offset = 0x0f8000,
    },
    ["Frames"] = {
      bank = 0x3e,
      address = 0x4800,
      offset = 0x0f8800,
    },
    ["MapGroupPalettes"] = {
      bank = 0x13,
      address = 0x4e05,
      offset = 0x04ce05,
    },
    ["MapObjectPals"] = {
      bank = 0x02,
      address = 0x7469,
      offset = 0x00b469,
    },
    ["PokemonNames"] = {
      bank = 0x14,
      address = 0x7384,
      offset = 0x053384,
    },
    ["TilesetBGPalette"] = {
      bank = 0x02,
      address = 0x7319,
      offset = 0x00b319,
    },
    ["TilesetIcePathGFX"] = {
      bank = 0x06,
      address = 0x660e,
      offset = 0x01a60e,
    },
    ["TilesetJohtoColl"] = {
      bank = 0x06,
      address = 0x640e,
      offset = 0x01a40e,
    },
    ["TilesetJohtoGFX"] = {
      bank = 0x06,
      address = 0x5006,
      offset = 0x019006,
    },
    ["TilesetJohtoMeta"] = {
      bank = 0x06,
      address = 0x5c0e,
      offset = 0x019c0e,
    },
    ["TilesetJohtoModernPalMap"] = {
      bank = 0x13,
      address = 0x4155,
      offset = 0x04c155,
    },
    ["TilesetJohtoPalMap"] = {
      bank = 0x13,
      address = 0x40e5,
      offset = 0x04c0e5,
    },
    ["Tilesets"] = {
      bank = 0x13,
      address = 0x5596,
      offset = 0x04d596,
    },
  },
}
