return {
  initialMap = { group = 24, map = 4, x = 13, y = 6 },
  groups = {
    {
      id = 24,
      name = "new_bark",
      extractMapIndexes = { 1, 2, 3, 4, 5, 6, 8, 9, 13 },
      maps = {
        "route_26",
        "route_27",
        "route_29",
        "new_bark_town",
        "elms_lab",
        "players_house_1f",
        "players_house_2f",
        "players_neighbors_house",
        "elms_house",
        "route_26_heal_house",
        "day_of_week_siblings_house",
        "route_27_sandstorm_house",
        "route_29_route_46_gate",
      },
    },
    {
      id = 26,
      name = "cherrygrove",
      extractMapIndexes = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 },
      maps = {
        "route_30",
        "route_31",
        "cherrygrove_city",
        "cherrygrove_mart",
        "cherrygrove_pokecenter_1f",
        "cherrygrove_gym_speech_house",
        "guide_gents_house",
        "cherrygrove_evolution_speech_house",
        "route_30_berry_house",
        "mr_pokemons_house",
        "route_31_violet_gate",
      },
    },
    {
      id = 10,
      name = "violet",
      extractMapIndexes = { 1, 3, 5, 6, 7, 8, 9, 10, 11 },
      maps = {
        "route_32",
        "route_35",
        "route_36",
        "route_37",
        "violet_city",
        "violet_mart",
        "violet_gym",
        "earls_pokemon_academy",
        "violet_nickname_speech_house",
        "violet_pokecenter_1f",
        "violet_kyles_house",
        "route_32_ruins_of_alph_gate",
        "route_32_pokecenter_1f",
        "route_35_goldenrod_gate",
        "route_35_national_park_gate",
        "route_36_ruins_of_alph_gate",
        "route_36_national_park_gate",
      },
    },
  },
}
