-- Generated by tools/generate_symbol_manifest.py; do not edit.
return {
  source = {
    repository = "https://github.com/pret/pokecrystal",
    sourceCommit = "3438c7003a57fa2987fcb223d14b660761b33c64",
    symbolsCommit = "0cc2d9450283fedfc43b02809884e77c76a9036c",
    symbolsSha256 = "b5c07188340954aaad30545ccb1593e3b1ffc21e22a983da98f3f642d5cb1382",
    rgbdsVersion = "1.0.1",
  },
  symbols = {
    ["BaseData"] = {
      bank = 0x14,
      address = 0x5424,
      offset = 0x051424,
    },
    ["BetaMonPicBanks"] = {
      bank = 0x14,
      address = 0x7d84,
      offset = 0x053d84,
    },
    ["CollisionPermissionTable"] = {
      bank = 0x13,
      address = 0x4e1f,
      offset = 0x04ce1f,
    },
    ["DiplomaPalettes"] = {
      bank = 0x02,
      address = 0x7641,
      offset = 0x00b641,
    },
    ["Font"] = {
      bank = 0x3e,
      address = 0x4200,
      offset = 0x0f8200,
    },
    ["FontBattleExtra"] = {
      bank = 0x3e,
      address = 0x4600,
      offset = 0x0f8600,
    },
    ["FontExtra"] = {
      bank = 0x3e,
      address = 0x4000,
      offset = 0x0f8000,
    },
    ["Frames"] = {
      bank = 0x3e,
      address = 0x4800,
      offset = 0x0f8800,
    },
    ["MapGroupPalettes"] = {
      bank = 0x13,
      address = 0x4e05,
      offset = 0x04ce05,
    },
    ["MapGroupPointers"] = {
      bank = 0x25,
      address = 0x4000,
      offset = 0x094000,
    },
    ["MapGroupRoofs"] = {
      bank = 0x07,
      address = 0x4021,
      offset = 0x01c021,
    },
    ["MapObjectPals"] = {
      bank = 0x02,
      address = 0x7469,
      offset = 0x00b469,
    },
    ["NewBarkTown_Blocks"] = {
      bank = 0x2b,
      address = 0x4db5,
      offset = 0x0acdb5,
    },
    ["NewBarkTown_MapAttributes"] = {
      bank = 0x25,
      address = 0x4dd8,
      offset = 0x094dd8,
    },
    ["NewBarkTown_MapEvents"] = {
      bank = 0x6a,
      address = 0x434d,
      offset = 0x1a834d,
    },
    ["OverworldSprites"] = {
      bank = 0x05,
      address = 0x4736,
      offset = 0x014736,
    },
    ["PokemonNames"] = {
      bank = 0x14,
      address = 0x7384,
      offset = 0x053384,
    },
    ["RoofPals"] = {
      bank = 0x02,
      address = 0x7569,
      offset = 0x00b569,
    },
    ["Roofs"] = {
      bank = 0x07,
      address = 0x403c,
      offset = 0x01c03c,
    },
    ["TilesetBGPalette"] = {
      bank = 0x02,
      address = 0x7319,
      offset = 0x00b319,
    },
    ["TilesetIcePathGFX"] = {
      bank = 0x06,
      address = 0x660e,
      offset = 0x01a60e,
    },
    ["TilesetJohtoColl"] = {
      bank = 0x06,
      address = 0x640e,
      offset = 0x01a40e,
    },
    ["TilesetJohtoGFX"] = {
      bank = 0x06,
      address = 0x5006,
      offset = 0x019006,
    },
    ["TilesetJohtoMeta"] = {
      bank = 0x06,
      address = 0x5c0e,
      offset = 0x019c0e,
    },
    ["TilesetJohtoModernPalMap"] = {
      bank = 0x13,
      address = 0x4155,
      offset = 0x04c155,
    },
    ["TilesetJohtoPalMap"] = {
      bank = 0x13,
      address = 0x40e5,
      offset = 0x04c0e5,
    },
    ["Tilesets"] = {
      bank = 0x13,
      address = 0x5596,
      offset = 0x04d596,
    },
  },
}
