-- Generated by tools/generate_symbol_manifest.py; do not edit.
return {
  source = {
    repository = "https://github.com/pret/pokecrystal",
    sourceCommit = "3438c7003a57fa2987fcb223d14b660761b33c64",
    symbolsCommit = "0cc2d9450283fedfc43b02809884e77c76a9036c",
    symbolsSha256 = "ca55588e83e4f4974e3872057eec12e8aac853bad1774e91486b5986cf6cb780",
    rgbdsVersion = "1.0.1",
  },
  symbols = {
    ["AcademyBlackboardText"] = {
      bank = 0x1a,
      address = 0x4eb2,
      offset = 0x068eb2,
    },
    ["AcademyEarlIntroText"] = {
      bank = 0x1a,
      address = 0x4b3b,
      offset = 0x068b3b,
    },
    ["AcademyNotebookText"] = {
      bank = 0x1a,
      address = 0x5136,
      offset = 0x069136,
    },
    ["AideText_AlwaysBusy"] = {
      bank = 0x1e,
      address = 0x5f65,
      offset = 0x079f65,
    },
    ["AideText_GiveYouPotion"] = {
      bank = 0x1e,
      address = 0x5f38,
      offset = 0x079f38,
    },
    ["ArthurGaveGiftText"] = {
      bank = 0x65,
      address = 0x4847,
      offset = 0x194847,
    },
    ["BaseData"] = {
      bank = 0x14,
      address = 0x5424,
      offset = 0x051424,
    },
    ["BetaMonPicBanks"] = {
      bank = 0x14,
      address = 0x7d84,
      offset = 0x053d84,
    },
    ["BirdKeeperAbeAfterBattleText"] = {
      bank = 0x1a,
      address = 0x48c7,
      offset = 0x0688c7,
    },
    ["BirdKeeperAbeSeenText"] = {
      bank = 0x1a,
      address = 0x487f,
      offset = 0x06887f,
    },
    ["BirdKeeperPeterAfterText"] = {
      bank = 0x64,
      address = 0x50d4,
      offset = 0x1910d4,
    },
    ["BirdKeeperRodAfterBattleText"] = {
      bank = 0x1a,
      address = 0x4837,
      offset = 0x068837,
    },
    ["BirdKeeperRodSeenText"] = {
      bank = 0x1a,
      address = 0x47cd,
      offset = 0x0687cd,
    },
    ["BugCatcherDonAfterText"] = {
      bank = 0x68,
      address = 0x5a1c,
      offset = 0x1a1a1c,
    },
    ["BugCatcherWade1AfterText"] = {
      bank = 0x69,
      address = 0x5671,
      offset = 0x1a5671,
    },
    ["CamperRolandAfterText"] = {
      bank = 0x64,
      address = 0x4faa,
      offset = 0x190faa,
    },
    ["CatchingTutorialDebriefText"] = {
      bank = 0x68,
      address = 0x514d,
      offset = 0x1a114d,
    },
    ["CatchingTutorialDeclinedText"] = {
      bank = 0x68,
      address = 0x5197,
      offset = 0x1a1197,
    },
    ["CatchingTutorialIntroText"] = {
      bank = 0x68,
      address = 0x50df,
      offset = 0x1a10df,
    },
    ["CherrygroveCitySignText"] = {
      bank = 0x67,
      address = 0x47e0,
      offset = 0x19c7e0,
    },
    ["CherrygroveEvolutionSpeechHouseLassText"] = {
      bank = 0x65,
      address = 0x6cfc,
      offset = 0x196cfc,
    },
    ["CherrygroveEvolutionSpeechHouseYoungsterText"] = {
      bank = 0x65,
      address = 0x6cc3,
      offset = 0x196cc3,
    },
    ["CherrygroveGymSpeechHouseBugCatcherText"] = {
      bank = 0x65,
      address = 0x6b65,
      offset = 0x196b65,
    },
    ["CherrygroveGymSpeechHousePokefanMText"] = {
      bank = 0x65,
      address = 0x6aea,
      offset = 0x196aea,
    },
    ["CherrygroveRivalText_Seen"] = {
      bank = 0x67,
      address = 0x44e2,
      offset = 0x19c4e2,
    },
    ["CherrygroveRivalText_YouLost"] = {
      bank = 0x67,
      address = 0x459e,
      offset = 0x19c59e,
    },
    ["CherrygroveRivalText_YouWon"] = {
      bank = 0x67,
      address = 0x4608,
      offset = 0x19c608,
    },
    ["CherrygroveTeacherText_HaveMapCard"] = {
      bank = 0x67,
      address = 0x46a8,
      offset = 0x19c6a8,
    },
    ["CherrygroveTeacherText_NoMapCard"] = {
      bank = 0x67,
      address = 0x4650,
      offset = 0x19c650,
    },
    ["CherrygroveYoungsterText_HavePokedex"] = {
      bank = 0x67,
      address = 0x4701,
      offset = 0x19c701,
    },
    ["CherrygroveYoungsterText_NoPokedex"] = {
      bank = 0x67,
      address = 0x46d6,
      offset = 0x19c6d6,
    },
    ["ChoseStarterText"] = {
      bank = 0x1e,
      address = 0x5487,
      offset = 0x079487,
    },
    ["ChrisPic"] = {
      bank = 0x22,
      address = 0x48a9,
      offset = 0x0888a9,
    },
    ["ChrisSpriteGFX"] = {
      bank = 0x30,
      address = 0x4000,
      offset = 0x0c0000,
    },
    ["CollisionPermissionTable"] = {
      bank = 0x13,
      address = 0x4e1f,
      offset = 0x04ce1f,
    },
    ["Cries"] = {
      bank = 0x3a,
      address = 0x51b0,
      offset = 0x0e91b0,
    },
    ["DarkCaveSignText"] = {
      bank = 0x69,
      address = 0x5a6e,
      offset = 0x1a5a6e,
    },
    ["DidntChooseStarterText"] = {
      bank = 0x1e,
      address = 0x544d,
      offset = 0x07944d,
    },
    ["DifficultBookshelfText"] = {
      bank = 0x6c,
      address = 0x435a,
      offset = 0x1b035a,
    },
    ["DiplomaPalettes"] = {
      bank = 0x02,
      address = 0x7641,
      offset = 0x00b641,
    },
    ["EarlsPokemonAcademyGameboyKid1Text"] = {
      bank = 0x1a,
      address = 0x4dda,
      offset = 0x068dda,
    },
    ["EarlsPokemonAcademyGameboyKid2Text"] = {
      bank = 0x1a,
      address = 0x4e07,
      offset = 0x068e07,
    },
    ["EarlsPokemonAcademySignText"] = {
      bank = 0x6a,
      address = 0x474d,
      offset = 0x1a874d,
    },
    ["EarlsPokemonAcademyYoungster1Text"] = {
      bank = 0x1a,
      address = 0x4d80,
      offset = 0x068d80,
    },
    ["EarlsPokemonAcademyYoungster2Text"] = {
      bank = 0x1a,
      address = 0x4e39,
      offset = 0x068e39,
    },
    ["ElmDescribesMrPokemonText"] = {
      bank = 0x1e,
      address = 0x560d,
      offset = 0x07960d,
    },
    ["ElmDirectionsText1"] = {
      bank = 0x1e,
      address = 0x54c0,
      offset = 0x0794c0,
    },
    ["ElmDirectionsText2"] = {
      bank = 0x1e,
      address = 0x5581,
      offset = 0x079581,
    },
    ["ElmDirectionsText3"] = {
      bank = 0x1e,
      address = 0x55db,
      offset = 0x0795db,
    },
    ["ElmPokeBallText"] = {
      bank = 0x1e,
      address = 0x5668,
      offset = 0x079668,
    },
    ["ElmText_Accepted"] = {
      bank = 0x1e,
      address = 0x50fa,
      offset = 0x0790fa,
    },
    ["ElmText_ChooseAPokemon"] = {
      bank = 0x1e,
      address = 0x52ff,
      offset = 0x0792ff,
    },
    ["ElmText_GotAnEmail"] = {
      bank = 0x1e,
      address = 0x51ae,
      offset = 0x0791ae,
    },
    ["ElmText_Intro"] = {
      bank = 0x1e,
      address = 0x4fb6,
      offset = 0x078fb6,
    },
    ["ElmText_LetYourMonBattleIt"] = {
      bank = 0x1e,
      address = 0x5375,
      offset = 0x079375,
    },
    ["ElmText_MissionFromMrPokemon"] = {
      bank = 0x1e,
      address = 0x51df,
      offset = 0x0791df,
    },
    ["ElmText_Refused"] = {
      bank = 0x1e,
      address = 0x511a,
      offset = 0x07911a,
    },
    ["ElmText_ResearchAmbitions"] = {
      bank = 0x1e,
      address = 0x513a,
      offset = 0x07913a,
    },
    ["ElmsLabHealingMachineText1"] = {
      bank = 0x1e,
      address = 0x5690,
      offset = 0x079690,
    },
    ["ElmsLabHealingMachineText2"] = {
      bank = 0x1e,
      address = 0x56aa,
      offset = 0x0796aa,
    },
    ["ElmsLabPCText"] = {
      bank = 0x1e,
      address = 0x63a6,
      offset = 0x07a3a6,
    },
    ["ElmsLabTrashcanText"] = {
      bank = 0x1e,
      address = 0x6370,
      offset = 0x07a370,
    },
    ["ElmsLabTravelTip1Text"] = {
      bank = 0x1e,
      address = 0x624c,
      offset = 0x07a24c,
    },
    ["ElmsLabTravelTip2Text"] = {
      bank = 0x1e,
      address = 0x628a,
      offset = 0x07a28a,
    },
    ["ElmsLabTravelTip3Text"] = {
      bank = 0x1e,
      address = 0x62c6,
      offset = 0x07a2c6,
    },
    ["ElmsLabTravelTip4Text"] = {
      bank = 0x1e,
      address = 0x6315,
      offset = 0x07a315,
    },
    ["ElmsLabWindowText1"] = {
      bank = 0x1e,
      address = 0x61fd,
      offset = 0x07a1fd,
    },
    ["ElmsLabWindowText2"] = {
      bank = 0x1e,
      address = 0x6231,
      offset = 0x07a231,
    },
    ["FalknerFightDoneText"] = {
      bank = 0x1a,
      address = 0x4735,
      offset = 0x068735,
    },
    ["FalknerIntroText"] = {
      bank = 0x1a,
      address = 0x4473,
      offset = 0x068473,
    },
    ["FalknerTMMudSlapText"] = {
      bank = 0x1a,
      address = 0x4648,
      offset = 0x068648,
    },
    ["FalknerWinLossText"] = {
      bank = 0x1a,
      address = 0x454a,
      offset = 0x06854a,
    },
    ["FalknerZephyrBadgeText"] = {
      bank = 0x1a,
      address = 0x45c8,
      offset = 0x0685c8,
    },
    ["FisherHenryAfterText"] = {
      bank = 0x64,
      address = 0x4df2,
      offset = 0x190df2,
    },
    ["FisherJustinAfterText"] = {
      bank = 0x64,
      address = 0x4b4e,
      offset = 0x190b4e,
    },
    ["FisherRalphAfterText"] = {
      bank = 0x64,
      address = 0x4bf8,
      offset = 0x190bf8,
    },
    ["FloriaText1"] = {
      bank = 0x65,
      address = 0x42f1,
      offset = 0x1942f1,
    },
    ["Font"] = {
      bank = 0x3e,
      address = 0x4200,
      offset = 0x0f8200,
    },
    ["FontBattleExtra"] = {
      bank = 0x3e,
      address = 0x4600,
      offset = 0x0f8600,
    },
    ["FontExtra"] = {
      bank = 0x3e,
      address = 0x4000,
      offset = 0x0f8000,
    },
    ["Frames"] = {
      bank = 0x3e,
      address = 0x4800,
      offset = 0x0f8800,
    },
    ["FriedaGaveGiftText"] = {
      bank = 0x64,
      address = 0x5222,
      offset = 0x191222,
    },
    ["GotElmsNumberText"] = {
      bank = 0x1e,
      address = 0x55f3,
      offset = 0x0795f3,
    },
    ["GotMapCardText"] = {
      bank = 0x67,
      address = 0x4438,
      offset = 0x19c438,
    },
    ["GuideGentGiftText"] = {
      bank = 0x67,
      address = 0x43ec,
      offset = 0x19c3ec,
    },
    ["GuideGentIntroText"] = {
      bank = 0x67,
      address = 0x41e3,
      offset = 0x19c1e3,
    },
    ["GuideGentMartText"] = {
      bank = 0x67,
      address = 0x4304,
      offset = 0x19c304,
    },
    ["GuideGentNoText"] = {
      bank = 0x67,
      address = 0x449f,
      offset = 0x19c49f,
    },
    ["GuideGentPokecenterText"] = {
      bank = 0x67,
      address = 0x4285,
      offset = 0x19c285,
    },
    ["GuideGentPokegearText"] = {
      bank = 0x67,
      address = 0x4451,
      offset = 0x19c451,
    },
    ["GuideGentRoute30Text"] = {
      bank = 0x67,
      address = 0x4359,
      offset = 0x19c359,
    },
    ["GuideGentSeaText"] = {
      bank = 0x67,
      address = 0x43a7,
      offset = 0x19c3a7,
    },
    ["GuideGentTourText1"] = {
      bank = 0x67,
      address = 0x426f,
      offset = 0x19c26f,
    },
    ["GuideGentsHouseGuideGentText"] = {
      bank = 0x65,
      address = 0x6c0d,
      offset = 0x196c0d,
    },
    ["GuideGentsHouseSignText"] = {
      bank = 0x67,
      address = 0x4815,
      offset = 0x19c815,
    },
    ["GymStatue_CityGymText"] = {
      bank = 0x6c,
      address = 0x474e,
      offset = 0x1b074e,
    },
    ["GymStatue_WinningTrainersText"] = {
      bank = 0x6c,
      address = 0x475c,
      offset = 0x1b075c,
    },
    ["JohtoGrassWildMons"] = {
      bank = 0x0a,
      address = 0x65e9,
      offset = 0x02a5e9,
    },
    ["JohtoWaterWildMons"] = {
      bank = 0x0a,
      address = 0x711d,
      offset = 0x02b11d,
    },
    ["KrisPic"] = {
      bank = 0x22,
      address = 0x4bb9,
      offset = 0x088bb9,
    },
    ["KrisSpriteGFX"] = {
      bank = 0x31,
      address = 0x7a40,
      offset = 0x0c7a40,
    },
    ["LabWhereGoingText"] = {
      bank = 0x1e,
      address = 0x53a7,
      offset = 0x0793a7,
    },
    ["MapGroupPalettes"] = {
      bank = 0x13,
      address = 0x4e05,
      offset = 0x04ce05,
    },
    ["MapGroupPointers"] = {
      bank = 0x25,
      address = 0x4000,
      offset = 0x094000,
    },
    ["MapGroupRoofs"] = {
      bank = 0x07,
      address = 0x4021,
      offset = 0x01c021,
    },
    ["MapObjectPals"] = {
      bank = 0x02,
      address = 0x7469,
      offset = 0x00b469,
    },
    ["MartSignText"] = {
      bank = 0x6c,
      address = 0x459c,
      offset = 0x1b059c,
    },
    ["MeetArthurText"] = {
      bank = 0x65,
      address = 0x4800,
      offset = 0x194800,
    },
    ["MeetFriedaText"] = {
      bank = 0x64,
      address = 0x51c1,
      offset = 0x1911c1,
    },
    ["MeetTuscanyText"] = {
      bank = 0x68,
      address = 0x53b2,
      offset = 0x1a13b2,
    },
    ["MrPokemonIntroText1"] = {
      bank = 0x65,
      address = 0x6f66,
      offset = 0x196f66,
    },
    ["MrPokemonIntroText2"] = {
      bank = 0x65,
      address = 0x6fa8,
      offset = 0x196fa8,
    },
    ["MrPokemonIntroText3"] = {
      bank = 0x65,
      address = 0x6feb,
      offset = 0x196feb,
    },
    ["MrPokemonIntroText4"] = {
      bank = 0x65,
      address = 0x7092,
      offset = 0x197092,
    },
    ["MrPokemonIntroText5"] = {
      bank = 0x65,
      address = 0x70b7,
      offset = 0x1970b7,
    },
    ["MrPokemonText_ImDependingOnYou"] = {
      bank = 0x65,
      address = 0x7134,
      offset = 0x197134,
    },
    ["MrPokemonsHouseDirectionsSignText"] = {
      bank = 0x68,
      address = 0x5b34,
      offset = 0x1a1b34,
    },
    ["MrPokemonsHouseSignText"] = {
      bank = 0x68,
      address = 0x5b55,
      offset = 0x1a1b55,
    },
    ["MrPokemonsHouse_BrokenComputerText"] = {
      bank = 0x65,
      address = 0x7584,
      offset = 0x197584,
    },
    ["MrPokemonsHouse_ForeignMagazinesText"] = {
      bank = 0x65,
      address = 0x7543,
      offset = 0x197543,
    },
    ["MrPokemonsHouse_GetDexText"] = {
      bank = 0x65,
      address = 0x73cc,
      offset = 0x1973cc,
    },
    ["MrPokemonsHouse_GotEggText"] = {
      bank = 0x65,
      address = 0x6fd2,
      offset = 0x196fd2,
    },
    ["MrPokemonsHouse_MrPokemonHealText"] = {
      bank = 0x65,
      address = 0x70ed,
      offset = 0x1970ed,
    },
    ["MrPokemonsHouse_OakText1"] = {
      bank = 0x65,
      address = 0x7185,
      offset = 0x197185,
    },
    ["MrPokemonsHouse_OakText2"] = {
      bank = 0x65,
      address = 0x73de,
      offset = 0x1973de,
    },
    ["Music_CherrygroveCity"] = {
      bank = 0x3d,
      address = 0x5b03,
      offset = 0x0f5b03,
    },
    ["Music_JohtoTrainerBattle"] = {
      bank = 0x3d,
      address = 0x6096,
      offset = 0x0f6096,
    },
    ["Music_LookRival"] = {
      bank = 0x3d,
      address = 0x4f79,
      offset = 0x0f4f79,
    },
    ["Music_Mom"] = {
      bank = 0x3d,
      address = 0x6bf2,
      offset = 0x0f6bf2,
    },
    ["Music_NewBarkTown"] = {
      bank = 0x3a,
      address = 0x72d3,
      offset = 0x0eb2d3,
    },
    ["Music_ProfOak"] = {
      bank = 0x3d,
      address = 0x4dea,
      offset = 0x0f4dea,
    },
    ["Music_Route29"] = {
      bank = 0x3c,
      address = 0x4386,
      offset = 0x0f0386,
    },
    ["Music_Route30"] = {
      bank = 0x3b,
      address = 0x7c01,
      offset = 0x0efc01,
    },
    ["Music_ShowMeAround"] = {
      bank = 0x3b,
      address = 0x5bd8,
      offset = 0x0edbd8,
    },
    ["Music_VioletCity"] = {
      bank = 0x3c,
      address = 0x4000,
      offset = 0x0f0000,
    },
    ["MysticWaterGuyTextBefore"] = {
      bank = 0x67,
      address = 0x4766,
      offset = 0x19c766,
    },
    ["NewBarkTownElmsHouseSignText"] = {
      bank = 0x6a,
      address = 0x4340,
      offset = 0x1a8340,
    },
    ["NewBarkTownElmsLabSignText"] = {
      bank = 0x6a,
      address = 0x4332,
      offset = 0x1a8332,
    },
    ["NewBarkTownPlayersHouseSignText"] = {
      bank = 0x6a,
      address = 0x4328,
      offset = 0x1a8328,
    },
    ["NewBarkTownRivalText1"] = {
      bank = 0x6a,
      address = 0x42a6,
      offset = 0x1a82a6,
    },
    ["NewBarkTownRivalText2"] = {
      bank = 0x6a,
      address = 0x42cd,
      offset = 0x1a82cd,
    },
    ["NewBarkTownSignText"] = {
      bank = 0x6a,
      address = 0x42e8,
      offset = 0x1a82e8,
    },
    ["NewBarkTown_Blocks"] = {
      bank = 0x2b,
      address = 0x4db5,
      offset = 0x0acdb5,
    },
    ["NewBarkTown_MapAttributes"] = {
      bank = 0x25,
      address = 0x4dd8,
      offset = 0x094dd8,
    },
    ["NewBarkTown_MapEvents"] = {
      bank = 0x6a,
      address = 0x434d,
      offset = 0x1a834d,
    },
    ["OverworldSprites"] = {
      bank = 0x05,
      address = 0x4736,
      offset = 0x014736,
    },
    ["PicnickerLiz1AfterText"] = {
      bank = 0x64,
      address = 0x5060,
      offset = 0x191060,
    },
    ["PokecenterSignText"] = {
      bank = 0x6c,
      address = 0x457f,
      offset = 0x1b057f,
    },
    ["PokemonCries"] = {
      bank = 0x3c,
      address = 0x6787,
      offset = 0x0f2787,
    },
    ["PokemonNames"] = {
      bank = 0x14,
      address = 0x7384,
      offset = 0x053384,
    },
    ["PokemonPalettes"] = {
      bank = 0x02,
      address = 0x68ce,
      offset = 0x00a8ce,
    },
    ["PokemonProfPic"] = {
      bank = 0x56,
      address = 0x415e,
      offset = 0x15815e,
    },
    ["PsychicMarkAfterBattleText"] = {
      bank = 0x65,
      address = 0x471e,
      offset = 0x19471e,
    },
    ["ReceivedStarterText"] = {
      bank = 0x1e,
      address = 0x54ad,
      offset = 0x0794ad,
    },
    ["ReceivedZephyrBadgeText"] = {
      bank = 0x1a,
      address = 0x45af,
      offset = 0x0685af,
    },
    ["RockSmashGuyText1"] = {
      bank = 0x65,
      address = 0x446f,
      offset = 0x19446f,
    },
    ["RoofPals"] = {
      bank = 0x02,
      address = 0x7569,
      offset = 0x00b569,
    },
    ["Roofs"] = {
      bank = 0x07,
      address = 0x403c,
      offset = 0x01c03c,
    },
    ["Route29CooltrainerMText_WaitingForMorning"] = {
      bank = 0x68,
      address = 0x537c,
      offset = 0x1a137c,
    },
    ["Route29CooltrainerMText_WaitingForNight"] = {
      bank = 0x68,
      address = 0x534c,
      offset = 0x1a134c,
    },
    ["Route29FisherText"] = {
      bank = 0x68,
      address = 0x52d9,
      offset = 0x1a12d9,
    },
    ["Route29Route46GateOfficerText"] = {
      bank = 0x1e,
      address = 0x75c1,
      offset = 0x07b5c1,
    },
    ["Route29Route46GateYoungsterText"] = {
      bank = 0x1e,
      address = 0x760d,
      offset = 0x07b60d,
    },
    ["Route29Sign1Text"] = {
      bank = 0x68,
      address = 0x558e,
      offset = 0x1a158e,
    },
    ["Route29TeacherText"] = {
      bank = 0x68,
      address = 0x526c,
      offset = 0x1a126c,
    },
    ["Route29YoungsterText"] = {
      bank = 0x68,
      address = 0x5214,
      offset = 0x1a1214,
    },
    ["Route30BerrySpeechHouseCheckTreesText"] = {
      bank = 0x65,
      address = 0x6dec,
      offset = 0x196dec,
    },
    ["Route30BerrySpeechHouseMonEatBerriesText"] = {
      bank = 0x65,
      address = 0x6d82,
      offset = 0x196d82,
    },
    ["Route30CooltrainerFText"] = {
      bank = 0x68,
      address = 0x5ac4,
      offset = 0x1a1ac4,
    },
    ["Route30SignText"] = {
      bank = 0x68,
      address = 0x5b0b,
      offset = 0x1a1b0b,
    },
    ["Route30TrainerTipsText"] = {
      bank = 0x68,
      address = 0x5b66,
      offset = 0x1a1b66,
    },
    ["Route30YoungsterText_DirectionsToMrPokemonsHouse"] = {
      bank = 0x68,
      address = 0x5a6a,
      offset = 0x1a1a6a,
    },
    ["Route30YoungsterText_EveryoneIsBattling"] = {
      bank = 0x68,
      address = 0x5a94,
      offset = 0x1a1a94,
    },
    ["Route31CooltrainerMText"] = {
      bank = 0x69,
      address = 0x55ff,
      offset = 0x1a55ff,
    },
    ["Route31SignText"] = {
      bank = 0x69,
      address = 0x5a45,
      offset = 0x1a5a45,
    },
    ["Route31VioletGateCooltrainerFText"] = {
      bank = 0x65,
      address = 0x7661,
      offset = 0x197661,
    },
    ["Route31VioletGateOfficerText"] = {
      bank = 0x65,
      address = 0x763a,
      offset = 0x19763a,
    },
    ["Route31YoungsterText"] = {
      bank = 0x69,
      address = 0x59d5,
      offset = 0x1a59d5,
    },
    ["Route32CooltrainerMText_ExperiencesShouldBeUseful"] = {
      bank = 0x64,
      address = 0x4a15,
      offset = 0x190a15,
    },
    ["Route32CooltrainerMText_WhatsTheHurry"] = {
      bank = 0x64,
      address = 0x4790,
      offset = 0x190790,
    },
    ["Route32RuinsSignText"] = {
      bank = 0x64,
      address = 0x535e,
      offset = 0x19135e,
    },
    ["Route32SignText"] = {
      bank = 0x64,
      address = 0x533a,
      offset = 0x19133a,
    },
    ["Route32UnionCaveSignText"] = {
      bank = 0x64,
      address = 0x537b,
      offset = 0x19137b,
    },
    ["Route36LassText"] = {
      bank = 0x65,
      address = 0x4626,
      offset = 0x194626,
    },
    ["Route36SignText"] = {
      bank = 0x65,
      address = 0x4924,
      offset = 0x194924,
    },
    ["Route36TrainerTips1Text"] = {
      bank = 0x65,
      address = 0x494c,
      offset = 0x19494c,
    },
    ["Route36TrainerTips2Text"] = {
      bank = 0x65,
      address = 0x49ee,
      offset = 0x1949ee,
    },
    ["RuinsOfAlphNorthSignText"] = {
      bank = 0x65,
      address = 0x492e,
      offset = 0x19492e,
    },
    ["SchoolboyAlanBooksText"] = {
      bank = 0x65,
      address = 0x47aa,
      offset = 0x1947aa,
    },
    ["Sfx_CaughtMon"] = {
      bank = 0x3c,
      address = 0x4c89,
      offset = 0x0f0c89,
    },
    ["Sfx_GetBadge"] = {
      bank = 0x3c,
      address = 0x517d,
      offset = 0x0f117d,
    },
    ["Sfx_GlassTing"] = {
      bank = 0x3c,
      address = 0x6769,
      offset = 0x0f2769,
    },
    ["Sfx_Menu"] = {
      bank = 0x3c,
      address = 0x494d,
      offset = 0x0f094d,
    },
    ["Sfx_RegisterPhoneNumber"] = {
      bank = 0x3c,
      address = 0x4dc7,
      offset = 0x0f0dc7,
    },
    ["Sfx_Sandstorm"] = {
      bank = 0x3c,
      address = 0x4b2a,
      offset = 0x0f0b2a,
    },
    ["Sfx_Tackle"] = {
      bank = 0x3c,
      address = 0x4a76,
      offset = 0x0f0a76,
    },
    ["Sfx_WarpFrom"] = {
      bank = 0x3c,
      address = 0x496e,
      offset = 0x0f096e,
    },
    ["Shrink1Pic"] = {
      bank = 0x13,
      address = 0x5249,
      offset = 0x04d249,
    },
    ["Shrink2Pic"] = {
      bank = 0x13,
      address = 0x52d9,
      offset = 0x04d2d9,
    },
    ["SproutTowerSignText"] = {
      bank = 0x6a,
      address = 0x4724,
      offset = 0x1a8724,
    },
    ["SudowoodoAttackedText"] = {
      bank = 0x65,
      address = 0x42aa,
      offset = 0x1942aa,
    },
    ["TakeChikoritaText"] = {
      bank = 0x1e,
      address = 0x541f,
      offset = 0x07941f,
    },
    ["TakeCyndaquilText"] = {
      bank = 0x1e,
      address = 0x53c8,
      offset = 0x0793c8,
    },
    ["TakeTotodileText"] = {
      bank = 0x1e,
      address = 0x53f3,
      offset = 0x0793f3,
    },
    ["Text_CallMomOnGear"] = {
      bank = 0x6a,
      address = 0x4236,
      offset = 0x1a8236,
    },
    ["Text_EarlAsksIfYouBeatFalkner"] = {
      bank = 0x6a,
      address = 0x4473,
      offset = 0x1a8473,
    },
    ["Text_ElmDiscoveredNewMon"] = {
      bank = 0x6a,
      address = 0x4274,
      offset = 0x1a8274,
    },
    ["Text_FollowEarl"] = {
      bank = 0x6a,
      address = 0x44cb,
      offset = 0x1a84cb,
    },
    ["Text_GearIsImpressive"] = {
      bank = 0x6a,
      address = 0x40f7,
      offset = 0x1a80f7,
    },
    ["Text_HereTeacherIAm"] = {
      bank = 0x6a,
      address = 0x44f9,
      offset = 0x1a84f9,
    },
    ["Text_ItsDangerousToGoAlone"] = {
      bank = 0x6a,
      address = 0x415e,
      offset = 0x1a815e,
    },
    ["Text_MillionDollarSlowpokeTail"] = {
      bank = 0x64,
      address = 0x4a59,
      offset = 0x190a59,
    },
    ["Text_RefusedToBuySlowpokeTail"] = {
      bank = 0x64,
      address = 0x4afc,
      offset = 0x190afc,
    },
    ["Text_RoarIntro"] = {
      bank = 0x64,
      address = 0x5133,
      offset = 0x191133,
    },
    ["Text_RoarOutro"] = {
      bank = 0x64,
      address = 0x518c,
      offset = 0x19118c,
    },
    ["Text_Route31SleepyMan"] = {
      bank = 0x69,
      address = 0x56d9,
      offset = 0x1a56d9,
    },
    ["Text_TellMomIfLeaving"] = {
      bank = 0x6a,
      address = 0x41f2,
      offset = 0x1a81f2,
    },
    ["Text_ThisIsABigBattle"] = {
      bank = 0x68,
      address = 0x581c,
      offset = 0x1a181c,
    },
    ["Text_ThoughtKidsWereLoaded"] = {
      bank = 0x64,
      address = 0x4acf,
      offset = 0x190acf,
    },
    ["Text_UseTackle"] = {
      bank = 0x68,
      address = 0x5806,
      offset = 0x1a1806,
    },
    ["Text_VeryNiceIndeed"] = {
      bank = 0x6a,
      address = 0x44ac,
      offset = 0x1a84ac,
    },
    ["Text_WaitPlayer"] = {
      bank = 0x6a,
      address = 0x4134,
      offset = 0x1a8134,
    },
    ["Text_WhatDoYouThinkYoureDoing"] = {
      bank = 0x6a,
      address = 0x413e,
      offset = 0x1a813e,
    },
    ["Text_YourMonIsAdorable"] = {
      bank = 0x6a,
      address = 0x41c4,
      offset = 0x1a81c4,
    },
    ["TilesetBGPalette"] = {
      bank = 0x02,
      address = 0x7319,
      offset = 0x00b319,
    },
    ["TilesetIcePathGFX"] = {
      bank = 0x06,
      address = 0x660e,
      offset = 0x01a60e,
    },
    ["TilesetJohtoColl"] = {
      bank = 0x06,
      address = 0x640e,
      offset = 0x01a40e,
    },
    ["TilesetJohtoGFX"] = {
      bank = 0x06,
      address = 0x5006,
      offset = 0x019006,
    },
    ["TilesetJohtoMeta"] = {
      bank = 0x06,
      address = 0x5c0e,
      offset = 0x019c0e,
    },
    ["TilesetJohtoModernPalMap"] = {
      bank = 0x13,
      address = 0x4155,
      offset = 0x04c155,
    },
    ["TilesetJohtoPalMap"] = {
      bank = 0x13,
      address = 0x40e5,
      offset = 0x04c0e5,
    },
    ["Tilesets"] = {
      bank = 0x13,
      address = 0x5596,
      offset = 0x04d596,
    },
    ["TimeSetBackgroundGFX"] = {
      bank = 0x24,
      address = 0x48fb,
      offset = 0x0908fb,
    },
    ["TimeSetDownArrowGFX"] = {
      bank = 0x24,
      address = 0x490b,
      offset = 0x09090b,
    },
    ["TimeSetUpArrowGFX"] = {
      bank = 0x24,
      address = 0x4903,
      offset = 0x090903,
    },
    ["TrainerGroups"] = {
      bank = 0x0e,
      address = 0x5999,
      offset = 0x039999,
    },
    ["TrainerPalettes"] = {
      bank = 0x02,
      address = 0x70ce,
      offset = 0x00b0ce,
    },
    ["TuscanyGaveGiftText"] = {
      bank = 0x68,
      address = 0x546f,
      offset = 0x1a146f,
    },
    ["TuscanyGivesGiftText"] = {
      bank = 0x68,
      address = 0x542f,
      offset = 0x1a142f,
    },
    ["UseSquirtbottleText"] = {
      bank = 0x65,
      address = 0x426b,
      offset = 0x19426b,
    },
    ["UsedSquirtbottleText"] = {
      bank = 0x65,
      address = 0x4290,
      offset = 0x194290,
    },
    ["VioletCityGrampsText"] = {
      bank = 0x6a,
      address = 0x45ef,
      offset = 0x1a85ef,
    },
    ["VioletCityLassText"] = {
      bank = 0x6a,
      address = 0x4529,
      offset = 0x1a8529,
    },
    ["VioletCitySignText"] = {
      bank = 0x6a,
      address = 0x46b2,
      offset = 0x1a86b2,
    },
    ["VioletCitySuperNerdText"] = {
      bank = 0x6a,
      address = 0x4593,
      offset = 0x1a8593,
    },
    ["VioletCityYoungsterText"] = {
      bank = 0x6a,
      address = 0x4665,
      offset = 0x1a8665,
    },
    ["VioletGymGuideText"] = {
      bank = 0x1a,
      address = 0x48f9,
      offset = 0x0688f9,
    },
    ["VioletGymGuideWinText"] = {
      bank = 0x1a,
      address = 0x49c8,
      offset = 0x0689c8,
    },
    ["VioletGymSignText"] = {
      bank = 0x6a,
      address = 0x46dc,
      offset = 0x1a86dc,
    },
    ["VioletKylesHousePokefanMText"] = {
      bank = 0x1a,
      address = 0x5997,
      offset = 0x069997,
    },
    ["VioletNicknameSpeechHouseBirdText"] = {
      bank = 0x1a,
      address = 0x547c,
      offset = 0x06947c,
    },
    ["VioletNicknameSpeechHouseLassText"] = {
      bank = 0x1a,
      address = 0x545e,
      offset = 0x06945e,
    },
    ["VioletNicknameSpeechHouseTeacherText"] = {
      bank = 0x1a,
      address = 0x53fa,
      offset = 0x0693fa,
    },
    ["WooperFrontpic"] = {
      bank = 0x55,
      address = 0x7846,
      offset = 0x157846,
    },
    ["YoungsterAlbertAfterText"] = {
      bank = 0x64,
      address = 0x4e82,
      offset = 0x190e82,
    },
    ["YoungsterGordonAfterText"] = {
      bank = 0x64,
      address = 0x4f49,
      offset = 0x190f49,
    },
    ["YoungsterJoey1AfterText"] = {
      bank = 0x68,
      address = 0x58c2,
      offset = 0x1a18c2,
    },
    ["YoungsterMikeyAfterText"] = {
      bank = 0x68,
      address = 0x597d,
      offset = 0x1a197d,
    },
    ["_AreYouABoyOrAreYouAGirlText"] = {
      bank = 0x70,
      address = 0x4ca3,
      offset = 0x1c0ca3,
    },
    ["_NPCTradeCableText"] = {
      bank = 0x6f,
      address = 0x5407,
      offset = 0x1bd407,
    },
    ["_NothingHereText"] = {
      bank = 0x6f,
      address = 0x4055,
      offset = 0x1bc055,
    },
    ["_OakText1"] = {
      bank = 0x70,
      address = 0x5d35,
      offset = 0x1c1d35,
    },
    ["_OakText2"] = {
      bank = 0x70,
      address = 0x5da4,
      offset = 0x1c1da4,
    },
    ["_OakText3"] = {
      bank = 0x70,
      address = 0x5de2,
      offset = 0x1c1de2,
    },
    ["_OakText4"] = {
      bank = 0x70,
      address = 0x5de5,
      offset = 0x1c1de5,
    },
    ["_OakText5"] = {
      bank = 0x70,
      address = 0x5e51,
      offset = 0x1c1e51,
    },
    ["_OakText6"] = {
      bank = 0x71,
      address = 0x4000,
      offset = 0x1c4000,
    },
    ["_OakText7"] = {
      bank = 0x71,
      address = 0x4026,
      offset = 0x1c4026,
    },
    ["_OakTimeHoursQuestionMarkText"] = {
      bank = 0x6f,
      address = 0x4305,
      offset = 0x1bc305,
    },
    ["_OakTimeHowManyMinutesText"] = {
      bank = 0x6f,
      address = 0x4308,
      offset = 0x1bc308,
    },
    ["_OakTimeMinutesQuestionMarkText"] = {
      bank = 0x6f,
      address = 0x4323,
      offset = 0x1bc323,
    },
    ["_OakTimeOversleptText"] = {
      bank = 0x6f,
      address = 0x4326,
      offset = 0x1bc326,
    },
    ["_OakTimeSoDarkText"] = {
      bank = 0x6f,
      address = 0x434f,
      offset = 0x1bc34f,
    },
    ["_OakTimeWhatHoursText"] = {
      bank = 0x6f,
      address = 0x42fd,
      offset = 0x1bc2fd,
    },
    ["_OakTimeWhatTimeIsItText"] = {
      bank = 0x6f,
      address = 0x42eb,
      offset = 0x1bc2eb,
    },
    ["_OakTimeWhoaMinutesText"] = {
      bank = 0x6f,
      address = 0x431b,
      offset = 0x1bc31b,
    },
    ["_OakTimeWokeUpText"] = {
      bank = 0x6f,
      address = 0x429c,
      offset = 0x1bc29c,
    },
    ["_OakTimeYikesText"] = {
      bank = 0x6f,
      address = 0x4336,
      offset = 0x1bc336,
    },
    ["_ObtainedFruitText"] = {
      bank = 0x6f,
      address = 0x402d,
      offset = 0x1bc02d,
    },
    ["_PlayerFoundItemText"] = {
      bank = 0x6f,
      address = 0x5321,
      offset = 0x1bd321,
    },
  },
}
