#!/usr/bin/env python3
"""Generate a compact Lua ROM-symbol manifest from pinned RGBDS output."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from dataclasses import dataclass
from pathlib import Path


SYMBOL_PATTERN = re.compile(
    r"^(?P<bank>[0-9A-Fa-f]+):(?P<address>[0-9A-Fa-f]{4})"
    r"[ \t]+(?P<label>\S+)[ \t]*$"
)
CONSTANT_PATTERN = re.compile(
    r"^[0-9A-Fa-f]+[ \t]+\S+[ \t]*$"
)


@dataclass(frozen=True)
class Symbol:
    bank: int
    address: int
    label: str

    @property
    def offset(self) -> int:
        if self.bank == 0:
            if self.address > 0x3FFF:
                raise ValueError(
                    f"{self.label}: bank 0 address is outside ROM0"
                )
            return self.address
        if self.address < 0x4000 or self.address > 0x7FFF:
            raise ValueError(
                f"{self.label}: banked address is outside ROMX"
            )
        return self.bank * 0x4000 + self.address - 0x4000


def parse_symbols(source: str) -> dict[str, Symbol]:
    symbols: dict[str, Symbol] = {}
    for line_number, raw_line in enumerate(source.splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith(";"):
            continue
        match = SYMBOL_PATTERN.fullmatch(line)
        if not match:
            if CONSTANT_PATTERN.fullmatch(line):
                continue
            raise ValueError(f"line {line_number}: malformed RGBDS symbol")

        symbol = Symbol(
            bank=int(match.group("bank"), 16),
            address=int(match.group("address"), 16),
            label=match.group("label"),
        )
        if symbol.label in symbols:
            raise ValueError(
                f"line {line_number}: duplicate symbol {symbol.label}"
            )
        symbols[symbol.label] = symbol
    return symbols


def parse_allowlist(source: str) -> list[str]:
    labels: list[str] = []
    seen: set[str] = set()
    for line_number, raw_line in enumerate(source.splitlines(), 1):
        label = raw_line.split("#", 1)[0].strip()
        if not label:
            continue
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.@#]*", label):
            raise ValueError(f"allowlist line {line_number}: invalid label")
        if label in seen:
            raise ValueError(f"allowlist line {line_number}: duplicate label")
        seen.add(label)
        labels.append(label)
    if not labels:
        raise ValueError("symbol allowlist is empty")
    return labels


def load_lock(path: Path) -> dict[str, object]:
    lock = json.loads(path.read_text(encoding="utf-8"))
    required = {
        "repository",
        "sourceCommit",
        "symbolsCommit",
        "symbolsPath",
        "symbolsSha256",
        "rgbdsVersion",
        "romProfile",
    }
    missing = sorted(required - lock.keys())
    if missing:
        raise ValueError("reference lock is missing: " + ", ".join(missing))
    for key in ("sourceCommit", "symbolsCommit"):
        if not re.fullmatch(r"[0-9a-f]{40}", str(lock[key])):
            raise ValueError(f"reference lock {key} is not a Git commit")
    if not re.fullmatch(r"[0-9a-f]{64}", str(lock["symbolsSha256"])):
        raise ValueError("reference lock symbolsSha256 is invalid")
    return lock


def render_manifest(
    selected: list[Symbol],
    lock: dict[str, object],
) -> str:
    lines = [
        "-- Generated by tools/generate_symbol_manifest.py; do not edit.",
        "return {",
        "  source = {",
        f'    repository = "{lock["repository"]}",',
        f'    sourceCommit = "{lock["sourceCommit"]}",',
        f'    symbolsCommit = "{lock["symbolsCommit"]}",',
        f'    symbolsSha256 = "{lock["symbolsSha256"]}",',
        f'    rgbdsVersion = "{lock["rgbdsVersion"]}",',
        "  },",
        "  symbols = {",
    ]
    for symbol in sorted(selected, key=lambda item: item.label):
        lines.extend(
            [
                f'    ["{symbol.label}"] = {{',
                f"      bank = 0x{symbol.bank:02x},",
                f"      address = 0x{symbol.address:04x},",
                f"      offset = 0x{symbol.offset:06x},",
                "    },",
            ]
        )
    lines.extend(["  },", "}", ""])
    return "\n".join(lines)


def generate(
    symbol_path: Path,
    allowlist_path: Path,
    lock_path: Path,
) -> str:
    lock = load_lock(lock_path)
    symbol_bytes = symbol_path.read_bytes()
    digest = hashlib.sha256(symbol_bytes).hexdigest()
    if digest != lock["symbolsSha256"]:
        raise ValueError(
            "RGBDS symbol file SHA-256 does not match the reference lock"
        )

    symbols = parse_symbols(symbol_bytes.decode("utf-8"))
    labels = parse_allowlist(allowlist_path.read_text(encoding="utf-8"))
    missing = [label for label in labels if label not in symbols]
    if missing:
        raise ValueError("required symbols are missing: " + ", ".join(missing))
    return render_manifest([symbols[label] for label in labels], lock)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--symbols", required=True, type=Path)
    parser.add_argument("--allowlist", required=True, type=Path)
    parser.add_argument("--lock", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    output = generate(args.symbols, args.allowlist, args.lock)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
